### ISSUE TITLE
ईङ् dhatu - Incorrect kartari nic luf forms and prakriya

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#120]
Reported by @vipranarayan14 :

> I think the [nic kartari luf forms of  ईङ् गतौ ०४.००३८](https://ashtadhyayi.com/dhatu/04.0038?tab=nich&scroll=dhatuform-1040038-nich-plung-0&scrollcolor=cyan&scrolloffset=400)  is wrong. Even the prakriya shown there is also seems weird. Please check. 

![image](https://github.com/ambuda-org/vidyut/assets/1429776/903edc59-386d-494e-b91e-5442bc331983)

> I think the forms should be as shown on the [sanskriabhyas](https://sanskritabhyas.in/%E0%A4%88-%E0%A4%A6%E0%A4%BF%E0%A4%B5%E0%A4%BE%E0%A4%A6%E0%A4%BF%E0%A4%83-%E0%A4%88%E0%A4%99%E0%A5%8D-%E0%A4%97%E0%A4%A4%E0%A5%8C%E2%80%A0%E0%A4%A3%E0%A4%BF%E0%A4%9A%E0%A5%8D-Dhatu-Roop) site:

![image](https://github.com/ambuda-org/vidyut/assets/1429776/95a872da-ed24-4a5f-bac6-ce965514366e)

> Please check. Also let me know if I am wrong.

**Comment by neeleshb** [comment]
1) In the prakriya for आयियत्, the द्वित्व is happening in presence of `चङ्`, hence the candidate of द्वित्व is `ई + णिच्`, and not the whole verb form namely  `ई  + णिच् + चङ् + त्`. So you should do the द्वित्व of `ई +णिच्` alone. That is,  first create `आयि`, then use `अजादेर्द्वितीयस्य `to do द्वित्व, giving `आयियि`. Combine that with `चङ् `and `तिप्`, giving `आयियिअत् `। This is followed by `णेरनिटि`, giving `आयियत्`, and the by `आडागम ` / `वृद्धि ` we get the final form as `आयियत्`.  (The same error can be seen for `उङ् शब्दे` (1.1102) as well).

2) Re the other forms, the generally accepted rule is that, in presence of `णिच् + चङ्,`  before you combine the verb with the `णिच्`, you should do द्वित्व first. So, in case of `असिस्रवत् `/ `असुस्रवत्`, we start with `स्रु + णिच् + चङ्`, then we do द्वित्व first, followed by `हलादिः शेषः`, giving `सु स्रु णिच् अ त्`. Now apply ` 7.4.81 स्रवति… `causing optional conversion of `सु `to `सि`, and then proceed further. 

3) But this raises a question -  in case `ई + णिच्`, why did we not follow the rule stated above? The answer is that , because `ई` is अजादि, the द्वित्व will affect not `ई` but rather it will affect the component after that (because of `अजादेर्द्वितीयस्य`). So we must obtain that component first. And the only way to do that is to combine the verb with `णिच्`. Hence we are required to complete the `ई + णिच्` prakriya first.

4) So in general, if the verb is अजादि, we need to  complete the णिच्-प्रक्रिया first.  But in all other cases, do the द्वित्व first, then अभ्यासकार्य if any, then णिच्कार्य.
